blood=read.csv("https://raw.githubusercontent.com/painel55/UCI-Blood-Transfusion-Service-Center-Data-Set-/master/transfusion.data.txt", header=FALSE)
blood$V5<- ifelse(is.na(blood$V5), ave(blood$V5, FUN = function(x)
mean(x, na.rm = TRUE)),blood$V5)
blood$Frequency..times.<- ifelse(is.na(blood$V2), ave(blood$V2, FUN = function(x)
mean(x, na.rm = TRUE)),blood$V2)
str(blood)
dim(blood)
tindex = sort(sample(nrow(blood), nrow(blood)*.7))
mtraining=blood[tindex,]
mtesting=blood[-tindex,]
library(e1071)
library(Metrics)
library(MLmetrics)
NB=naiveBayes(as.factor(mtraining$V5)~.,data=mtraining)
print(NB)
predNB1=predict(NB,mtesting,type="class")
set.seed(1)
length(mtesting$V5)
length(predNB1)
table(mtesting$V5,predNB1)
plot(predNB1)
Accuracy(predNB1,mtesting$V5)
